# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      name: Cache node modules
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.json') }}
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 20.x
    - uses: pnpm/action-setup@v3
      with:
        version: 8
    - run: pnpm ci --progress=false
    - run: pnpm lint
    - run: pnpm test

  packtest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      name: Cache node modules
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.json') }}
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 20.x
    - run: pnpm ci --progress=false
    - run: pnpm build
    - run: pnpm dlx attw $(pnpm pack)